# Generated by Django 5.2.4 on 2025-08-10 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('course', models.CharField(blank=True, choices=[('B.Tech', 'B.Tech'), ('B.Sc', 'B.Sc'), ('M.Sc', 'M.Sc'), ('MBA', 'MBA'), ('Other', 'Other')], max_length=50)),
                ('subject', models.CharField(blank=True, max_length=120)),
                ('semester', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('upload', models.FileField(upload_to='notes/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
