# Generated by Django 5.2.4 on 2025-08-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_download_count_alter_note_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='note_list/'),
        ),
    ]
