# Generated by Django 5.2.4 on 2026-01-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_event_remove_note_download_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
